eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
     hostname: localhost
spring:
  application:
    name: BOOKING-SERVICE 